import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowRight, BarChart3, Bitcoin, BriefcaseBusiness, CheckCircle2, Clock3, LineChart, Sparkles, TrendingUp } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { dataService } from "../lib/dataService";
import { createFlashInvestment, createWeeklyInvestment, processInvestmentTimers } from "../lib/investmentEngine";
import { EmptyState, Modal, PageHeader, StatusBadge } from "../components/UI";
import { TradingViewChart } from "../components/TradingViewWidget";
import { FlashCalculator, InvestmentCard, MiniBarChart, money, PlanCalculator, Timeline } from "../components/InvestmentUI";

function useLibrary(name, adminId) {
  const [items, setItems] = useState([]);
  useEffect(() => { dataService.list(name, adminId).then((result) => setItems(result.filter((item) => item.active))); }, [name, adminId]);
  return items;
}

function beginDeposit(navigate, investment, amount) {
  navigate(`/dashboard/deposit?investment=${investment.id}&week=${(investment.completedWeeks || 0) + 1}&amount=${amount}&asset=${encodeURIComponent(investment.ticker)}`);
}

export function FlashInvestmentPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [settings, setSettings] = useState(null); const [tiers, setTiers] = useState([]); const [selected, setSelected] = useState(null);
  useEffect(() => { Promise.all([dataService.list("flashSettings", user.adminId), dataService.list("flashTiers", user.adminId)]).then(([config, tierItems]) => { setSettings(config[0]); const active = tierItems.filter((item) => item.active); setTiers(active); setSelected(active[0]); }); }, [user.adminId]);
  async function invest() { const investment = await createFlashInvestment({ user, settings, tier: selected }); beginDeposit(navigate, investment, selected.capital); }
  if (!settings?.active) return <EmptyState icon={Clock3} title="Flash investment is currently unavailable" text="Your advisor will announce when new flash opportunities become available." />;
  return <div><PageHeader eyebrow="Short horizon" title={settings.name || "Flash Investment"} description="One deposit, a fixed maturity window, and a return credited only when the countdown completes." /><div className="grid gap-6 xl:grid-cols-[1fr_.8fr]"><div className="glass-card overflow-hidden"><div className="bg-navy p-7 text-white"><Sparkles className="text-gold" /><h2 className="display-title mt-6 text-3xl">Select a flash tier</h2><p className="mt-2 text-sm text-white/45">Each approved plan keeps its original capital, return, and duration.</p></div><div className="table-scroll overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-[10px] uppercase tracking-widest text-slate-400"><th className="px-6 py-4">Capital</th><th>Return after {settings.durationHours} hours</th><th /></tr></thead><tbody>{tiers.map((tier) => <tr key={tier.id} className={`border-t border-slate-100 ${selected?.id === tier.id ? "bg-gold/[.06]" : ""}`}><td className="px-6 py-5 font-bold text-navy">{money(tier.capital)}</td><td className="font-bold text-forest">{money(tier.returnAmount)}</td><td className="pr-6 text-right"><button onClick={() => setSelected(tier)} className="text-xs font-bold text-gold">{selected?.id === tier.id ? "Selected" : "Select"}</button></td></tr>)}</tbody></table></div></div><div><FlashCalculator tiers={tiers} durationHours={settings.durationHours} selectedTier={selected} onTierChange={setSelected} /><button onClick={invest} disabled={!selected} className="btn-primary mt-4 w-full py-4">Proceed to deposit <ArrowRight size={17} /></button><div className="glass-card mt-6 p-6"><p className="section-kicker">Build beyond flash</p><h3 className="display-title mt-2 text-2xl text-navy">Create a longer-term strategy.</h3><p className="mt-3 text-sm leading-6 text-slate-500">Explore weekly crypto and stock plans for structured portfolio growth.</p><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={() => navigate("/dashboard/crypto-investment")} className="btn-secondary text-navy"><Bitcoin size={16} /> Crypto</button><button onClick={() => navigate("/dashboard/stock-investment")} className="btn-secondary text-navy"><LineChart size={16} /> Stocks</button></div></div></div></div></div>;
}

export function CryptoInvestmentPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const coins = useLibrary("coins", user.adminId); const [selected, setSelected] = useState(null); const [tier, setTier] = useState(null); const [duration, setDuration] = useState(3);
  useEffect(() => { if (coins.length && !selected) { setSelected(coins[0]); setTier(coins[0].tiers.find((item) => item.active)); } }, [coins, selected]);
  function choose(coin) { setSelected(coin); setTier(coin.tiers.find((item) => item.active)); }
  async function invest() { const investment = await createWeeklyInvestment({ user, asset: selected, tier, durationMonths: duration, type: "crypto" }); beginDeposit(navigate, investment, tier.weeklyCapital); }
  return <div><PageHeader eyebrow="Digital asset desk" title="Crypto investments" description="Select an approved asset, choose a weekly commitment, and begin with your Week 1 deposit." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{coins.map((coin) => <button key={coin.id} onClick={() => choose(coin)} className={`glass-card p-5 text-left ${selected?.id === coin.id ? "border-gold ring-4 ring-gold/10" : ""}`}><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center overflow-hidden rounded-full bg-navy font-display text-xl font-bold text-gold">{coin.logoUrl ? <img src={coin.logoUrl} className="h-full w-full object-cover" /> : coin.ticker[0]}</span><div><p className="font-display text-xl font-bold text-navy">{coin.name}</p><p className="text-xs text-slate-400">{coin.ticker} · Live market</p></div></div></button>)}</div>{selected && <div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="glass-card p-3"><TradingViewChart symbol={selected.tradingViewSymbol} /></div><div><PlanCalculator tiers={selected.tiers.filter((item) => item.active)} selectedTier={tier} onTierChange={setTier} duration={duration} onDurationChange={setDuration} /><button onClick={invest} className="btn-primary mt-4 w-full py-4">Start {selected.ticker} plan <ArrowRight size={17} /></button></div></div>}</div>;
}

function nyseStatus() {
  const now = new Date();
  const ny = new Date(now.toLocaleString("en-US", { timeZone: "America/New_York" }));
  const day = ny.getDay(); const minutes = ny.getHours() * 60 + ny.getMinutes();
  const open = day >= 1 && day <= 5 && minutes >= 570 && minutes < 960;
  const next = new Date(ny);
  next.setHours(9, 30, 0, 0);
  if (minutes >= 960 || day === 0 || day === 6) next.setDate(next.getDate() + (day === 5 ? 3 : day === 6 ? 2 : day === 0 ? 1 : 1));
  return { open, next };
}

export function StockInvestmentPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const stocks = useLibrary("stocks", user.adminId); const market = nyseStatus();
  return <div><PageHeader eyebrow="Global equity desk" title="Stock investments" description="Research approved companies and establish a structured equity plan." /><div className={`mb-6 flex items-center justify-between rounded-2xl border p-5 ${market.open ? "border-emerald-200 bg-emerald-50" : "border-gold/30 bg-gold/10"}`}><div><p className="font-bold text-navy">NYSE market {market.open ? "open" : "closed"}</p><p className="mt-1 text-xs text-slate-500">{market.open ? "Regular session · 09:30-16:00 ET" : `Next session: ${market.next.toLocaleString()}`}</p></div><span className={`h-3 w-3 rounded-full ${market.open ? "bg-emerald-500" : "bg-gold"}`} /></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{stocks.map((stock) => <div key={stock.id} className="glass-card p-6"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center overflow-hidden rounded-xl bg-navy font-display text-lg font-bold text-gold">{stock.logoUrl ? <img src={stock.logoUrl} className="h-full w-full object-cover" /> : stock.ticker[0]}</span><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">+{(Math.random() * .8 + .1).toFixed(2)}%</span></div><h2 className="display-title mt-6 text-2xl text-navy">{stock.name}</h2><p className="mt-1 text-xs text-slate-400">{stock.ticker} · {stock.sector}</p><p className="mt-5 text-sm leading-6 text-slate-500">{stock.about}</p><button onClick={() => navigate(`/dashboard/stock-investment/${stock.id}`)} className="btn-primary mt-6 w-full">Research & invest <ArrowRight size={16} /></button></div>)}</div></div>;
}

export function StockResearchPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const { stockId } = useParams(); const [stock, setStock] = useState(null); const [tier, setTier] = useState(null); const [duration, setDuration] = useState(3);
  useEffect(() => { dataService.list("stocks", user.adminId).then((items) => { const found = items.find((item) => item.id === stockId); setStock(found); setTier(found?.tiers?.find((item) => item.active)); }); }, [stockId, user.adminId]);
  async function invest() { const investment = await createWeeklyInvestment({ user, asset: stock, tier, durationMonths: duration, type: "stock" }); beginDeposit(navigate, investment, tier.weeklyCapital); }
  if (!stock) return <div className="glass-card p-10 text-center">Loading company research...</div>;
  return <div><PageHeader eyebrow={`${stock.sector} · ${stock.ticker}`} title={stock.name} description={stock.about} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Market cap", stock.marketCap], ["52-week high", stock.weekHigh], ["52-week low", stock.weekLow], ["P/E ratio", stock.peRatio]].map(([label, value]) => <div key={label} className="glass-card p-5"><p className="text-[10px] uppercase tracking-widest text-slate-400">{label}</p><p className="display-title mt-2 text-2xl text-navy">{value}</p></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="glass-card p-3"><TradingViewChart symbol={stock.tradingViewSymbol} /></div><div className="space-y-6"><div className="glass-card p-6"><h2 className="display-title text-2xl text-navy">Why invest</h2><p className="mt-3 text-sm leading-7 text-slate-500">{stock.whyInvest}</p><p className="mt-4 border-t border-slate-100 pt-4 text-xs font-bold text-gold">{stock.historicalReturns}</p></div><PlanCalculator tiers={stock.tiers.filter((item) => item.active)} selectedTier={tier} onTierChange={setTier} duration={duration} onDurationChange={setDuration} /><button onClick={invest} className="btn-primary w-full py-4">Buy now / invest <BriefcaseBusiness size={17} /></button></div></div></div>;
}

export function PortfolioPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [investments, setInvestments] = useState([]); const [detail, setDetail] = useState(null);
  const load = useCallback(async () => { const items = await processInvestmentTimers(user.userId); setInvestments(items.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))); }, [user.userId]);
  useEffect(() => { load(); }, [load]);
  const stocks = investments.filter((item) => item.type === "stock" && !["deleted"].includes(item.status));
  return <div><PageHeader eyebrow="Investment book" title="My portfolio" description="Monitor every active, paused, flash, and completed Stonehaven plan." /><div className="grid gap-5 xl:grid-cols-2">{investments.map((item) => <InvestmentCard key={item.id} investment={item} onDeposit={(investment) => beginDeposit(navigate, investment, investment.capital || investment.weeklyCapital)} onDetails={setDetail} />)}</div>{!investments.length && <EmptyState icon={TrendingUp} title="No investments yet" text="Choose a flash, crypto, or stock plan to begin your portfolio." />}{stocks.length > 0 && <div className="glass-card mt-7 table-scroll overflow-x-auto"><div className="p-6"><h2 className="display-title text-2xl text-navy">Equity holdings</h2></div><table className="w-full min-w-[700px]"><thead><tr className="bg-navy text-left text-[10px] uppercase tracking-widest text-white/45"><th className="px-6 py-4">Stock</th><th>Shares</th><th>Bought at</th><th>Current value</th><th>P&L</th><th>Projected return</th></tr></thead><tbody>{stocks.map((item) => { const invested = item.completedWeeks * item.weeklyCapital; const fluctuation = 1 + (((item.id.length % 7) - 3) / 1000); const current = invested * fluctuation; return <tr key={item.id} className="border-b border-slate-100 text-sm"><td className="px-6 py-5 font-bold text-navy">{item.ticker}</td><td>{item.referencePrice ? (invested / item.referencePrice).toFixed(2) : "-"}</td><td>{money(invested)}</td><td>{money(current)}</td><td className={current >= invested ? "text-forest" : "text-burgundy"}>{money(current - invested)}</td><td>{money(item.projectedReturn)} locked</td></tr>; })}</tbody></table></div>}<Modal open={Boolean(detail)} onClose={() => setDetail(null)} title={detail?.planName || "Investment details"}>{detail && <Timeline investment={detail} />}</Modal></div>;
}

export function EarningsPage() {
  const { user } = useAuth(); const [items, setItems] = useState([]);
  useEffect(() => { dataService.listForUser("investments", user.userId).then((result) => setItems(result.filter((item) => ["completed", "flash done"].includes(item.status)))); }, [user.userId]);
  const total = items.reduce((sum, item) => sum + Number(item.projectedReturn || 0), 0);
  const best = Math.max(...items.map((item) => Number(item.projectedReturn || 0)), 0);
  const rates = items.map((item) => { const capital = item.type === "flash" ? item.capital : item.weeklyCapital * item.totalWeeks; return capital ? ((item.projectedReturn - capital) / capital) * 100 : 0; });
  const average = rates.length ? rates.reduce((a, b) => a + b, 0) / rates.length : 0;
  const months = useMemo(() => Array.from({ length: 12 }, (_, index) => { const date = new Date(); date.setMonth(date.getMonth() - (11 - index)); const value = items.filter((item) => { const completed = new Date(item.completedAt); return completed.getMonth() === date.getMonth() && completed.getFullYear() === date.getFullYear(); }).reduce((sum, item) => sum + item.projectedReturn, 0); return { label: date.toLocaleString("en-US", { month: "short" }), value }; }), [items]);
  const assets = Object.entries(items.reduce((acc, item) => ({ ...acc, [item.ticker]: (acc[item.ticker] || 0) + item.projectedReturn }), {})).sort((a, b) => b[1] - a[1]);
  return <div><PageHeader eyebrow="Performance reporting" title="Earnings statistics" description="Completed-plan returns, asset contribution, and monthly maturity history." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total earned", money(total)], ["Best single return", money(best)], ["Average return rate", `${average.toFixed(1)}%`], ["Plans completed", items.length]].map(([label, value]) => <div key={label} className="glass-card p-6"><p className="text-[10px] uppercase tracking-widest text-slate-400">{label}</p><p className="display-title mt-3 text-3xl text-navy">{value}</p></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><div className="glass-card p-7"><h2 className="display-title text-2xl text-navy">Monthly earnings</h2><MiniBarChart values={months} /></div><div className="glass-card p-7"><h2 className="display-title text-2xl text-navy">Per asset</h2><div className="mt-6 space-y-5">{assets.map(([asset, value]) => <div key={asset}><div className="flex justify-between text-sm"><span className="font-bold text-navy">{asset}</span><span>{money(value)}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-gold" style={{ width: `${total ? (value / total) * 100 : 0}%` }} /></div></div>)}{!assets.length && <p className="text-sm text-slate-400">Completed plans will populate this breakdown.</p>}</div></div></div><div className="glass-card mt-6 table-scroll overflow-x-auto"><table className="w-full min-w-[700px]"><thead><tr className="bg-navy text-left text-[10px] uppercase tracking-widest text-white/45"><th className="px-6 py-4">Plan</th><th>Asset</th><th>Capital</th><th>Return</th><th>Completed</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b border-slate-100 text-sm"><td className="px-6 py-5 font-bold text-navy">{item.planName}</td><td>{item.ticker}</td><td>{money(item.capital || item.weeklyCapital * item.totalWeeks)}</td><td className="font-bold text-forest">{money(item.projectedReturn)}</td><td>{new Date(item.completedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></div>;
}

